name: Deploy to AWS ECR & EC2

on:
    push:
        branches:
            - main # main 브랜치에 push될 때 실행

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 코드
              uses: actions/checkout@v3

            - name: ECR 로그인
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
                  AWS_REGION: ap-northeast-2
              run: |
                  aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 180294215847.dkr.ecr.ap-northeast-2.amazonaws.com

            - name: Docker 이미지 빌드 및 푸시
              run: |
                  docker build -t 180294215847.dkr.ecr.ap-northeast-2.amazonaws.com/dylan-app:latest .
                  docker push 180294215847.dkr.ecr.ap-northeast-2.amazonaws.com/dylan-app:latest

            - name: EC2에 SSH 키 등록
              run: |
                  echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ec2_key.pem
                  chmod 600 ec2_key.pem

            - name: EC2에서 배포 스크립트 실행
              run: |
                  ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.AWS_EC2_IP }} "bash /home/ubuntu/deploy_ecr.sh"
